export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const CREATE_COURSE = "CREATE_COURSE";
export const COURSE_DATA_TO_COMPONENT = "COURSE_DATA_TO_COMPONENT"; // All courses data
export const CURRENT_COURSE_DATA_TO_COMPONENT = "CURRENT_COURSE_DATA_TO_COMPONENT"; // Current course data
export const ANNOUNCEMENT_CREATE = "ANNOUNCEMENT_CREATE";
export const REGISTER = "REGISTER";
export const EDIT = "EDIT";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
